# Generated by Django 5.1.7 on 2025-03-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('language', models.CharField(max_length=50, verbose_name='Язык курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_files/', verbose_name='Файл')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('order', models.PositiveIntegerField(verbose_name='Очередность урока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
        ),
    ]
