# Generated by Django 5.1.7 on 2025-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность (мин)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность (мин)'),
        ),
    ]
