# Generated by Django 5.2 on 2025-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_category_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_instal',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/attachments/', verbose_name='Файл для скачивания (ДЗ/материалы)'),
        ),
    ]
